project:
  type: website

website:
  title: "today"
  navbar:
    left:
      - href: index.qmd
        text: home
      - text: Blog
        menu: 
        - 01_workflow.qmd
      - about.qmd
  sidebar:
    contents: auto

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true